AWSTemplateFormatVersion: '2010-09-09'
Description: VPC with Public and Private Subnets

Parameters:
  AvailabilityZone1:
    Type: String
    Description: Availability Zone for the first subnet (e.g., us-east-1a)
  AvailabilityZone2:
    Type: String
    Description: Availability Zone for the second subnet (e.g., us-east-1b)

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      AvailabilityZone: !Ref AvailabilityZone1
      CidrBlock: 10.0.1.0/24

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      AvailabilityZone: !Ref AvailabilityZone2
      CidrBlock: 10.0.2.0/24

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      AvailabilityZone: !Ref AvailabilityZone1
      CidrBlock: 10.0.3.0/24

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      AvailabilityZone: !Ref AvailabilityZone2
      CidrBlock: 10.0.4.0/24
